Filter sort by
MissMelisa/countries pull request #4
Opened 2021-04-28 15:53 UTC by MissMelisa

Add a new filter to classify countries by language, borders, and areas
![image](https://user-images.githubusercontent.com/77803702/116434287-ac6a4e80-a820-11eb-93a0-d80af71d25d2.png)

2021-04-30 19:57 UTC, falecci requested changes

2021-04-30 19:57 UTC, falecci commented on src/Components/Countries.jsx
> +  borders: PropTypes.number,
`borders` should be a `string`, right?

2021-04-30 19:57 UTC, falecci commented on src/Components/Countries.jsx
> +        <span className={styles.infoStyle}>Borders: {borders || 0}</span>
Since `borders` is a string, shouldn't the default value be something like `NONE` or `-` instead of 0?

2021-05-10 18:56 UTC, MissMelisa commented on src/Components/Countries.jsx
> +        <span className={styles.infoStyle}>Borders: {borders || 0}</span>
checked it

2021-05-10 18:56 UTC, MissMelisa commented on src/Components/Countries.jsx
> +        <span className={styles.infoStyle}>Borders: {borders || 0}</span>
![image](https://user-images.githubusercontent.com/77803702/117710292-55f9fa00-b1a8-11eb-81c5-53396d633e83.png)

2021-05-18 15:27 UTC, falecci approved these changes

2021-05-18 16:05 UTC, merged